name: talent8.com.au
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75048
title: Global Talent Acquisition Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0077b4'
    - '#fdd001'
    - '#022d47'
    - '#6f5700'
  brandStrength: 0.625
  lightness: 0.7437978400848806
  saturation: 0.4410951135214418
  rhythmicContrast: 0.5
purpose: []
