name: talent8.com.au
favicon: null
layout_spectrum: 0.7630786313675344
typography_spectrum: 0.8738305759616196
title: Global Talent Acquisition Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#021631'
    - '#d1d1d1'
    - '#14b6db'
    - '#0f7d96'
    - '#878e97'
  brandStrength: 0.625
  lightness: 0.7437978400848806
  saturation: 0.4410951135214418
  rhythmicContrast: 0.5
purpose: []
