name: talent8.com.au
favicon: null
layout_spectrum: 0.3387097
typography_spectrum: 0.4677419
title: Home
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: www.talent8.com.au
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0077b4'
    - '#fdd001'
    - '#022d47'
    - '#6f5700'
  brandStrength: 0.7222222
  lightness: 0.001792115
  saturation: 1
  rhythmicContrast: 0.8548387
purpose: []
